spring:
  profiles: common

tencent:
  cloud:
    appId: 1326451774
    secretId:
    secretKey:
    region-public: ap-guangzhou
    bucket-public: fmdj-public-1326451774
    region-private: ap-guangzhou
    bucket-private: fmdj-1326451774
  map:
    key: 111
wx:
  app-id: wxa4a547bf9c56ff29
  app-secret: 8b6ba3bce7206e7070b9eebae9e7d105
  mch-id: 111
  key: 222
#  cert-path: 333

minio:
  endpoint: http://14.103.42.241:9000
  access-key: root
  secret-key: yiliaoxiangmu123

